In [1]:
import numpy as np

# 1. Create a 3x3x3 array with random values 

In [2]:
x = np.random.randint(100,size=(3,3,3))
print(x)

[[[35 92 30]
  [87 66 82]
  [34 13  4]]

 [[62 60 94]
  [58 15 53]
  [11 30 66]]

 [[ 9 63 41]
  [18 41 89]
  [ 8 23 46]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
a=np.zeros((8,8),dtype=int)
a[1::2,::2]=1
a[::2,1::2]=1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [5]:
x = np.random.random((5, 5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.28331355 0.83765985 0.05439175 0.4229712  0.62443326]
 [0.80742925 0.9772498  0.53780498 0.82294287 0.82728772]
 [0.24424963 0.01998161 0.65056032 0.69226402 0.45324159]
 [0.25827744 0.05814705 0.26441288 0.54771325 0.38323561]
 [0.1261694  0.00207201 0.32038704 0.78435762 0.32135595]]
After normalization:
[[0.28840027 0.85685692 0.05365149 0.43161277 0.63820285]
 [0.82585683 1.         0.54936954 0.84176534 0.84622078]
 [0.24834202 0.01836547 0.66499496 0.70776018 0.46265367]
 [0.26272689 0.05750238 0.26901851 0.55953001 0.39086575]
 [0.12725618 0.         0.32641743 0.80219793 0.327411  ]]


# 5.  How to find common values between two arrays?

In [6]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ", array1)
array2 = [10, 30, 40]
print("Array2: ", array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [7]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ", yesterday)
today = np.datetime64('today', 'D')
print("Today: ", today)
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ", tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [8]:
x = np.random.randint(0,6,6)
print("First array:")
print(x)
y = np.random.randint(0,6,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[4 3 2 1 0 2]
Second array:
[3 3 2 4 3 1]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [9]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a[a.argmax()]=0
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

# 9. How to print all the values of an array?

In [10]:
c=np.array([1,2,3,5,6,7,8,9,22,3443,444])
for i in c:
    print(i,end=" ")

1 2 3 5 6 7 8 9 22 3443 444 

# 10.Subtract the mean of each row of a matrix

In [11]:
f=np.arange(9)
f=f.reshape(3,3)
print(f,"\n\n")
Y = f - f.mean(axis=1, keepdims=True)
Y

[[0 1 2]
 [3 4 5]
 [6 7 8]] 




array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [12]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 4. 1. 4. 1. 4. 3. 5. 1. 6.]


# 12.How to get the diagonal of a dot product?

In [13]:
c=np.array([[1,2],[3,4]])
d=np.array([[5,6],[7,8]])
e=np.dot(c,d)
e.diagonal()

array([19, 50])

# 13.How to find the most frequent value in an array?

In [14]:
x = np.random.randint(0, 10, 400)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[0 9 1 2 3 8 6 3 0 4 6 5 2 3 5 2 3 3 0 0 0 4 6 3 0 5 6 6 5 0 4 7 3 3 7 0 6
 2 6 8 5 1 3 4 0 6 0 7 8 0 0 2 6 4 8 3 6 0 6 7 8 9 2 5 9 5 9 2 1 8 5 0 2 0
 3 0 3 1 6 0 6 6 0 7 0 4 6 5 0 5 2 7 4 4 4 3 2 0 0 5 7 4 0 0 8 1 9 2 1 8 4
 3 5 8 8 3 8 3 7 6 9 4 6 7 1 3 8 2 7 9 5 3 4 2 6 1 7 2 1 4 2 7 6 0 4 9 7 1
 2 4 7 9 8 4 1 5 7 6 8 6 5 0 3 6 2 2 5 7 1 5 8 3 9 7 4 4 4 9 3 3 2 0 1 6 9
 6 3 8 1 4 5 7 7 1 3 6 6 9 5 9 7 2 4 5 0 1 9 4 2 4 1 3 7 2 0 9 2 5 3 9 3 3
 8 4 4 1 9 8 2 7 8 6 8 5 1 7 4 3 1 1 2 8 4 5 1 5 4 6 3 2 9 9 8 5 2 2 8 4 9
 4 2 9 0 3 2 4 7 0 9 5 7 1 6 8 1 6 6 2 3 8 8 3 9 8 3 7 0 2 7 4 3 0 6 7 9 8
 7 4 9 8 9 8 2 4 7 6 4 5 8 4 1 7 9 2 8 5 0 1 1 1 9 4 1 7 6 3 2 0 7 6 8 7 4
 2 2 2 6 8 7 1 5 6 7 2 9 3 9 0 4 7 6 7 5 8 6 6 7 5 4 8 4 5 2 9 1 3 6 7 7 0
 1 9 9 1 0 5 2 9 4 2 2 8 0 8 3 1 4 1 3 1 3 4 9 5 3 8 2 4 6 6]
Most frequent value in the above array:
4


# 14.How to get the n largest values of an array

In [15]:
a=np.array([1,2,3,66,778,33,7458])

a[a.argmax()]

7458

# 15.How to create a record array from a regular array?

In [16]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')

In [17]:
print(Z)
print(R)

[['Hello' '2.5' '3']
 ['World' '3.6' '2']]
[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
